dirtyInputs: true
id: 97f87182-252c-454b-810d-c951e39abe9d
inputSections:
- description: Generic group for inputs
  inputs:
  - incident_id
  name: General (Inputs group)
inputs:
- description: ""
  key: incident_id
  playbookInputQuery: null
  required: true
  value: {}
name: Close Incidents
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
quiet: true
starttaskid: "0"
tags:
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e3a4ffd5-adb5-49d4-8e54-715805207555
      iscommand: false
      name: ""
      version: -1
    taskid: e3a4ffd5-adb5-49d4-8e54-715805207555
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: errorPath
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "8"
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: '{"request_data":{"incident_id":"${inputs.incident_id}","update_data":{"status":"resolved_other","resolve_comment":"Resolved
          by the Auto Triage Job"}}}'
      uri:
        simple: /public_api/v1/incidents/update_incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: send HTTP POST request.
      id: 958e2c9a-4f9e-41f8-a617-1ca32f65d965
      iscommand: true
      name: Close Incident
      script: '|||core-api-post'
      type: regular
      version: -1
    taskid: 958e2c9a-4f9e-41f8-a617-1ca32f65d965
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 380
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 30aae18e-e9ed-45b0-8572-85c9a7ca5b0e
      iscommand: false
      name: Fin
      type: title
      version: -1
    taskid: 30aae18e-e9ed-45b0-8572-85c9a7ca5b0e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 720
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 70396ca7-33b0-4663-833f-a495a53c1793
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: 70396ca7-33b0-4663-833f-a495a53c1793
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 550
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.incident_id
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b20b3f16-cdd7-478f-a3e1-30e50f48027d
      iscommand: false
      name: Is there an Incident ID?
      type: condition
      version: -1
    taskid: b20b3f16-cdd7-478f-a3e1-30e50f48027d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 210
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 730,
        "width": 671.5,
        "x": 50,
        "y": 50
      }
    }
  }
