dirtyInputs: true
id: Foundation - Upon Trigger
inputSections:
- description: Generic group for inputs
  inputs: []
  name: General (Inputs group)
inputs: []
name: Foundation - Upon Trigger
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs:
  - Shadow
outputs:
- contextPath: Shadow
  type: boolean
quiet: true
starttaskid: "0"
tags:
- SOC
- PoV
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5206068f-fdf3-4829-8cc2-c3ada7b5516b
      iscommand: false
      name: ""
      version: -1
    taskid: 5206068f-fdf3-4829-8cc2-c3ada7b5516b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cd6cbd33-49b9-4c0e-8c76-12c43c541cb5
      iscommand: false
      name: Environment Detection
      type: title
      version: -1
    taskid: cd6cbd33-49b9-4c0e-8c76-12c43c541cb5
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eaffbc30-3533-483b-80c1-82bdd0e73dd3
      iscommand: false
      name: Data Integrity
      type: title
      version: -1
    taskid: eaffbc30-3533-483b-80c1-82bdd0e73dd3
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 715
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2b3a538a-4c64-408a-86b2-74cd81484c7f
      iscommand: false
      name: Incident Sync (Ledger / Owner Notification)
      type: title
      version: -1
    taskid: 2b3a538a-4c64-408a-86b2-74cd81484c7f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 880
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4bc7c9d9-c8d2-4e49-8f24-1e964e9ad270
      iscommand: false
      name: Dedup
      type: title
      version: -1
    taskid: 4bc7c9d9-c8d2-4e49-8f24-1e964e9ad270
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a4730ca6-80a0-4fb3-80d3-9a2e6e1f964c
      iscommand: false
      name: Enrichment (User, IP, Hash, Domain)
      type: title
      version: -1
    taskid: a4730ca6-80a0-4fb3-80d3-9a2e6e1f964c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1370
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 35c54f0f-e1e7-48a9-8aed-57d322ddf9c7
      iscommand: false
      name: Assessment
      type: title
      version: -1
    taskid: 35c54f0f-e1e7-48a9-8aed-57d322ddf9c7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1700
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 76dd4bf8-4839-4846-8cc2-95492ce2721a
      iscommand: false
      name: Escalation
      type: title
      version: -1
    taskid: 76dd4bf8-4839-4846-8cc2-95492ce2721a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1860
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d6a23a94-520a-4ff6-8146-c309f064e6ed
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d6a23a94-520a-4ff6-8146-c309f064e6ed
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 2020
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: alert.env
          operator: isEqualString
          right:
            value:
              simple: prod
      label: "yes"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "18"
      "yes":
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      retry-count:
        simple: "0"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d1f1473c-003c-4c82-ac5a-07e0e82dad09
      iscommand: false
      name: Is this a Production Environment?
      type: condition
      version: -1
    taskid: d1f1473c-003c-4c82-ac5a-07e0e82dad09
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 371
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: errorPath
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "24"
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: shadow_mode
      value:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 67eedc50-5c07-4832-896d-f5b9780eb669
      iscommand: false
      name: Set To Shadow
      script: Set
      type: regular
      version: -1
    taskid: 67eedc50-5c07-4832-896d-f5b9780eb669
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 100,
          "y": 540
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: errorPath
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "24"
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: shadow_mode
      value:
        simple: "false"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 5752dc90-12fe-48dd-99df-2df4c8d2a051
      iscommand: false
      name: Set To Full Run
      script: Set
      type: regular
      version: -1
    taskid: 5752dc90-12fe-48dd-99df-2df4c8d2a051
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 581,
          "y": 540
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: A simple Dedup to insure alerts are not executed on more than once.
      id: affbdad4-0d9f-4822-8ff0-30bdda250e0e
      iscommand: false
      name: Foundation - Dedup
      playbookId: Foundation - Dedup
      type: playbook
      version: -1
    taskid: affbdad4-0d9f-4822-8ff0-30bdda250e0e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1200
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bf804660-d518-4cd7-87b5-4a5cbd2f4b47
      iscommand: false
      name: Foundation - Enrichment
      playbookId: Foundation - Enrichment
      type: playbook
      version: -1
    taskid: bf804660-d518-4cd7-87b5-4a5cbd2f4b47
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1530
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: bba69d32-a3b9-4a81-8d58-1be1e99e119f
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: bba69d32-a3b9-4a81-8d58-1be1e99e119f
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 631,
          "y": 710
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2030,
        "width": 962,
        "x": 50,
        "y": 50
      }
    }
  }
