dirtyInputs: true
id: ba7aa520-0767-4b3c-87ed-79e32b5ad5dd
inputSections:
- description: Generic group for inputs
  inputs:
  - Shadow
  name: General (Inputs group)
inputs:
- description: In Shadow Mode the Playbook will run in a testing only mode where it
    prints to the war room but will not take disruptive actions
  key: Shadow
  playbookInputQuery: null
  required: true
  value:
    simple: "false"
name: Use Case - Proofpoint Click Permitted
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
sourceplaybookid: fcd8a90f-5f53-4dc4-8ade-48374a66b4ec
starttaskid: "0"
tags:
- SOC
- PoV
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0b9d53d3-d66f-4715-8249-de216ec9808d
      iscommand: false
      name: ""
      version: -1
    taskid: 0b9d53d3-d66f-4715-8249-de216ec9808d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: errorPath
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "12"
    note: true
    quietmode: 2
    scriptarguments:
      ignore-outputs:
        simple: "false"
      includeCampaignForensics:
        simple: "true"
      threatId:
        simple: ${alert.proofpointtapthreatid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns forensics evidence.
      id: 86e46687-7f40-48f4-8581-8dcb8c77cfbb
      iscommand: true
      name: Get Forensic Information
      script: '|||proofpoint-get-forensics'
      type: regular
      version: -1
    taskid: 86e46687-7f40-48f4-8581-8dcb8c77cfbb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 540
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: errorPath
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      forensicsummarymarkdown:
        complex:
          accessor: Report
          root: Proofpoint
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: bf746e5f-94ec-4ab2-a00a-04c9090adc6b
      iscommand: true
      name: Summarize Forensic Info
      script: Builtin|||setAlert
      type: regular
      version: -1
    taskid: bf746e5f-94ec-4ab2-a00a-04c9090adc6b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 880
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Proofpoint.Report
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5ddb3b42-ec1a-4353-83d7-f3760fa60739
      iscommand: false
      name: Forensic Info Exists?
      type: condition
      version: -1
    taskid: 5ddb3b42-ec1a-4353-83d7-f3760fa60739
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 710
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: errorPath
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "20"
      - "15"
    note: false
    quietmode: 2
    reputationcalc: 2
    scriptarguments:
      text:
        simple: |-
          ${alert.proofpointtapsuspiciousurl}
          ${alert.proofpointtapclickip}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.extract.indicators
      id: a4444626-37ea-4f61-8016-7e1c62cfcf14
      iscommand: true
      name: Create Indicator from Threat
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: a4444626-37ea-4f61-8016-7e1c62cfcf14
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 545.25,
          "y": 1210
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b9b18ac2-1779-4228-8ca6-a1ee4314025e
      iscommand: false
      name: TIM - Enrichment
      type: title
      version: -1
    taskid: b9b18ac2-1779-4228-8ca6-a1ee4314025e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 545.25,
          "y": 1050
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: errorPath
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      indicator:
        simple: ${alert.proofpointtapsuspiciousurl}
      indicatorType:
        simple: url
      reliability:
        simple: C - Fairly reliable
      score:
        simple: "2"
      vendor:
        simple: Proofpoint
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Add DBot score to context for indicators with custom vendor, score,
        reliability, and type.
      id: 9f8fb9ec-0c9c-4ea3-a4f4-092bbb5c77a4
      iscommand: false
      name: Assign Proofpoint DBot Score
      script: AddDBotScoreToContext
      type: regular
      version: -1
    taskid: 9f8fb9ec-0c9c-4ea3-a4f4-092bbb5c77a4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1316.75,
          "y": 1550
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: errorPath
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${alert.proofpointtapsuspiciousurl}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the overall score for the indicator as calculated by DBot.
      id: b003a1b1-11d6-4477-b3f5-3a95816d709b
      iscommand: false
      name: Get Indicator Scores
      script: GetIndicatorDBotScoreFromCache
      type: regular
      version: -1
    taskid: b003a1b1-11d6-4477-b3f5-3a95816d709b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1316.75,
          "y": 1720
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScoreCache.Score
          operator: greaterThan
          right:
            value:
              simple: "2"
        - left:
            iscontext: true
            value:
              simple: Proofpoint.Report.Behavior.Malicious
          operator: isTrue
        - left:
            iscontext: true
            value:
              simple: Core.value
          operator: isFalse
      label: "yes"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "18"
      "yes":
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9f6de37e-1303-49e7-8715-08e10901e086
      iscommand: false
      name: Remediation Required?
      type: condition
      version: -1
    taskid: 9f6de37e-1303-49e7-8715-08e10901e086
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1607.25,
          "y": 2220
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: errorPath
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "29"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 90be9cad-92ee-4bf8-b131-395cdc8abd2f
      iscommand: true
      name: Close
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 90be9cad-92ee-4bf8-b131-395cdc8abd2f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1607.25,
          "y": 2720
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 89886dee-4e3e-4c9f-8414-ad151cc66e54
      iscommand: false
      name: Analysis
      type: title
      version: -1
    taskid: 89886dee-4e3e-4c9f-8414-ad151cc66e54
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1462,
          "y": 1890
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: errorPath
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "21"
    note: true
    quietmode: 0
    scriptarguments:
      url:
        simple: ${alert.proofpointtapsuspiciousurl}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Converts the contents of a URL to an image file or a PDF file.
      id: f3f1911d-d1f7-48b5-8506-3a3655ec3287
      iscommand: true
      name: Rasterize URL
      script: '|||rasterize'
      type: regular
      version: -1
    taskid: f3f1911d-d1f7-48b5-8506-3a3655ec3287
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 640.5,
          "y": 1380
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: errorPath
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "26"
    note: true
    quietmode: 0
    scriptarguments:
      method:
        simple: GET
      url:
        simple: ${alert.proofpointtapsuspiciousurl}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends http request. Returns the response as json.
      id: 8b4d6890-9876-4204-8a06-a9aaae936420
      iscommand: false
      name: Request raw HTML
      script: http
      type: regular
      version: -1
    taskid: 8b4d6890-9876-4204-8a06-a9aaae936420
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 690.5,
          "y": 1550
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6284baff-3fb9-461a-889d-645f171e605c
      iscommand: false
      name: Forensics
      type: title
      version: -1
    taskid: 6284baff-3fb9-461a-889d-645f171e605c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 380
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4e618c0d-6718-4b0f-85f9-d7084050e938
      iscommand: false
      name: Remediation
      type: title
      version: -1
    taskid: 4e618c0d-6718-4b0f-85f9-d7084050e938
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1752.5,
          "y": 2390
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: errorPath
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: Core=.
      ip_address:
        simple: ${alert.labels.clickIP}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the prevalence of an ip, identified by ip_address.
      id: 0d98aacf-4892-478e-8371-446585b5adb0
      iscommand: true
      name: Prevalence of Click IP
      script: '|||core-get-IP-analytics-prevalence'
      type: regular
      version: -1
    taskid: 0d98aacf-4892-478e-8371-446585b5adb0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1462,
          "y": 2050
        }
      }
  "26":
    continueonerror: true
    continueonerrortype: errorPath
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      forensicdnsmarkdown:
        complex:
          accessor: DNS
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      forensicfilemarkdown:
        complex:
          accessor: File
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      forensicnetworkmarkdown:
        complex:
          accessor: Network
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      forensicsummarymarkdown:
        complex:
          accessor: Behavior
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      httpcookiesmd:
        complex:
          accessor: Cookies
          root: HttpRequest.Response
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      httprawhtml:
        simple: ${HttpRequest.Response.Body}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: f3626359-1539-4b91-ab41-5aab6522c99c
      iscommand: true
      name: Set Response Data
      script: Builtin|||setAlert
      type: regular
      version: -1
    taskid: f3626359-1539-4b91-ab41-5aab6522c99c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 835.75,
          "y": 1720
        }
      }
  "27":
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b4f0dbea-65db-4be4-8a39-2b45a5e42882
      iscommand: false
      name: Manual Review
      type: regular
      version: -1
    taskid: b4f0dbea-65db-4be4-8a39-2b45a5e42882
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1752.5,
          "y": 2550
        }
      }
  "28":
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 569f89b6-a611-445d-83c7-b651ab245a10
      iscommand: false
      name: Foundation - Upon Trigger
      playbookId: Foundation - Upon Trigger
      type: playbook
      version: -1
    taskid: 569f89b6-a611-445d-83c7-b651ab245a10
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 210
        }
      }
  "29":
    continueonerrortype: ""
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f3d3b6e4-8232-4808-87dd-ee2e280cd321
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f3d3b6e4-8232-4808-87dd-ee2e280cd321
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1026.25,
          "y": 3060
        }
      }
  "30":
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "29"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: fc8e2675-f51f-4110-888e-980fb44da7cb
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: fc8e2675-f51f-4110-888e-980fb44da7cb
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 550,
          "y": 2890
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3070,
        "width": 2083.5,
        "x": 50,
        "y": 50
      }
    }
  }
