dirtyInputs: true
id: 19afce31-d945-4a44-800d-efd460f0c9f1
inputs: []
name: Use Case - Close NGFW Prevented
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5481d500-924e-4af3-8d69-bf6a98b670f6
      iscommand: false
      name: ""
      version: -1
    taskid: 5481d500-924e-4af3-8d69-bf6a98b670f6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: errorPath
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "5"
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: eb94ae43-7086-45b8-9a09-e5608fd76c1e
      iscommand: true
      name: Close Alert
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: eb94ae43-7086-45b8-9a09-e5608fd76c1e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 550
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: errorPath
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "5"
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      type:
        simple: NGFW Prevented
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 891a1c35-05d3-4761-8710-2a955027bf3c
      iscommand: true
      name: Set Alert Type
      script: Builtin|||setAlert
      type: regular
      version: -1
    taskid: 891a1c35-05d3-4761-8710-2a955027bf3c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 380
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bce720e8-ee1f-4559-98c6-9f1b7b91ccd2
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: bce720e8-ee1f-4559-98c6-9f1b7b91ccd2
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 890
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: aa707ddf-9ee8-4384-8ba6-6f5b0aeb3f07
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: aa707ddf-9ee8-4384-8ba6-6f5b0aeb3f07
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: e0ffc94d-1fc8-4b14-8ed6-3aa3ba72daba
      iscommand: false
      name: Foundation - Upon Trigger
      playbookId: Foundation - Upon Trigger
      type: playbook
      version: -1
    taskid: e0ffc94d-1fc8-4b14-8ed6-3aa3ba72daba
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 210
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 900,
        "width": 671.5,
        "x": 50,
        "y": 50
      }
    }
  }
