dirtyInputs: true
id: 6dc67d0e-6eb9-4097-8787-8260b0cf7ab4
inputs: []
name: Utility - Emergency Alert Resolver
outputs: []
sourceplaybookid: da4ddd5b-fd19-419b-862b-23f64feed129
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: faa4b177-4b1a-499e-8f40-3ca8a888c9ac
      iscommand: false
      name: ""
      version: -1
    taskid: faa4b177-4b1a-499e-8f40-3ca8a888c9ac
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b1ae301c-1a22-4b54-87a6-a63c4c0ee824
      iscommand: false
      name: CloseAlerts
      script: a5051b65-b8e8-4111-88e7-44e193a8ea3e
      type: regular
      version: -1
    taskid: b1ae301c-1a22-4b54-87a6-a63c4c0ee824
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
